# Generated by Django 5.0.3 on 2024-05-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racer',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='racer',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='racer',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
