# Generated by Django 5.0.3 on 2024-05-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racer', '0002_racer_date_racer_email_racer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='date',
            field=models.IntegerField(null=True),
        ),
    ]
