# Generated by Django 5.0.3 on 2024-06-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racer', '0004_zavod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zavod',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
