# Generated by Django 5.0.3 on 2024-06-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racer', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterField(
            model_name='racer',
            name='lastname',
            field=models.CharField(max_length=255),
        ),
    ]
