# Generated by Django 5.0.3 on 2024-06-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racer', '0008_delete_profile_alter_racer_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='racer',
            name='choice_field',
            field=models.CharField(choices=[('M', 'muž'), ('F', 'žena')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='racer',
            name='sex',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
