# Generated by Django 5.0.3 on 2024-06-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racer', '0009_racer_choice_field_racer_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racer',
            name='choice_field',
        ),
        migrations.AlterField(
            model_name='racer',
            name='sex',
            field=models.CharField(choices=[('M', 'muž'), ('F', 'žena')], max_length=10, null=True),
        ),
    ]
